### ISSUE TITLE
多次尝试滑条验证后报错

### ISSUE THREAD

**Issue by Kroytz** [VidocqH/ff14_checkin#1]
> Error: Protocol error (Input.dispatchMouseEvent): Invalid parameters Failed to deserialize params.x - BINDINGS: double value expected at position 37
> Error: Protocol error (Input.dispatchMouseEvent): Invalid parameters Failed to deserialize params.x - BINDINGS: double value expected at position 37
> /Users/runner/work/ff14_checkin/ff14_checkin/node_modules/opencv-wasm/opencv.js:94
>                             throw ex
>                             ^
> 
> RuntimeError: abort(Error: Protocol error (Input.dispatchMouseEvent): Invalid parameters Failed to deserialize params.x - BINDINGS: double value expected at position 37). Build with -s ASSERTIONS=1 for more info.
>     at process.abort (/Users/runner/work/ff14_checkin/ff14_checkin/node_modules/opencv-wasm/opencv.js:775:27)
>     at process.emit (events.js:315:20)
>     at processPromiseRejections (internal/process/promises.js:245:33)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by VidocqH** [comment]
#2

**Comment by Kroytz** [comment]
本人直接使用了Action, 设置完Repo secrets后试着Run workflow, 在约6分钟后(10次左右?)报的这个错误
这次是17分钟, 疑似遇到特殊图像会这样翻车?

**Comment by VidocqH** [comment]
![C6FCBE58-B0E4-48D7-BE48-9F5411052392](https://user-images.githubusercontent.com/16725418/111454785-040c9900-8750-11eb-859e-94b828a1cef5.jpeg)
是因为开了异地登录保护 尝试信任下美国？ GitHub的服务器在美国

**Comment by Kroytz** [comment]
成功了. 我之前登录保护是关闭的, 开启后信任美国与上海, 甚至不用滑条认证

> Run node ./index.js
> 填写账号
> 填写密码
> 开始滑块认证
> 登陆成功
> 开始选择大区
> 开始选择角色
> 查询到 角色：*** 服务器：***
> 确认角色选择
> 开始签到
> 签到完成
> 你今天已经签到过了！
> 当前积分: 109,000
> server酱发送通知消息成功

但我在第二次试运行之后发现了新的错误

> 填写账号
> 填写密码
> 开始滑块认证
> 滑块认证尝试失败（正常情况，无法做到100%过滑块），刷新网页重试
> 填写账号
> 填写密码
> 开始滑块认证
> 登陆成功
> 开始选择大区
> 开始选择角色
> 查询到 角色：*** 服务器：***
> 确认角色选择
> 开始签到
> 签到完成
> 你今天已经签到过了！
> 当前积分: 109,000
> 登陆成功
> Error: Node is either not visible or not an HTMLElement
> Error: Node is either not visible or not an HTMLElement
> /Users/runner/work/ff14_checkin/ff14_checkin/node_modules/opencv-wasm/opencv.js:94
>                             throw ex
>                             ^
> 
> RuntimeError: abort(Error: Node is either not visible or not an HTMLElement). Build with -s ASSERTIONS=1 for more info.
>     at process.abort (/Users/runner/work/ff14_checkin/ff14_checkin/node_modules/opencv-wasm/opencv.js:775:27)
>     at process.emit (events.js:315:20)
>     at processPromiseRejections (internal/process/promises.js:245:33)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> Error: Process completed with exit code 7.

不过无伤大雅, 签到也成功了. Push翻车而已.
感谢大佬的幻想科技!!

**Comment by VidocqH** [comment]
> 成功了. 我之前登录保护是关闭的, 开启后信任美国与上海, 甚至不用滑条认证
> 
> > Run node ./index.js
> > 填写账号
> > 填写密码
> > 开始滑块认证
> > 登陆成功
> > 开始选择大区
> > 开始选择角色
> > 查询到 角色：*** 服务器：***
> > 确认角色选择
> > 开始签到
> > 签到完成
> > 你今天已经签到过了！
> > 当前积分: 109,000
> > server酱发送通知消息成功
> 
> 但我在第二次试运行之后发现了新的错误
> 
> > 填写账号
> > 填写密码
> > 开始滑块认证
> > 滑块认证尝试失败（正常情况，无法做到100%过滑块），刷新网页重试
> > 填写账号
> > 填写密码
> > 开始滑块认证
> > 登陆成功
> > 开始选择大区
> > 开始选择角色
> > 查询到 角色：*** 服务器：***
> > 确认角色选择
> > 开始签到
> > 签到完成
> > 你今天已经签到过了！
> > 当前积分: 109,000
> > 登陆成功
> > Error: Node is either not visible or not an HTMLElement
> > Error: Node is either not visible or not an HTMLElement
> > /Users/runner/work/ff14_checkin/ff14_checkin/node_modules/opencv-wasm/opencv.js:94
> > throw ex
> > ^
> > RuntimeError: abort(Error: Node is either not visible or not an HTMLElement). Build with -s ASSERTIONS=1 for more info.
> > at process.abort (/Users/runner/work/ff14_checkin/ff14_checkin/node_modules/opencv-wasm/opencv.js:775:27)
> > at process.emit (events.js:315:20)
> > at processPromiseRejections (internal/process/promises.js:245:33)
> > at processTicksAndRejections (internal/process/task_queues.js:94:32)
> > Error: Process completed with exit code 7.
> 
> 不过无伤大雅, 签到也成功了. Push翻车而已.
> 感谢大佬的幻想科技!!

这个我昨天康到了，但是既然签到成功了就不太想动233
![image](https://user-images.githubusercontent.com/16725418/111484760-016e6b80-8771-11eb-8a8a-71dcd19b4e3d.png)
